template_path: lambda-func.yaml
parameters:
  DBName: postgres
  DBPassword: postgres
  DBUser: postgres
  SourceCodeBucket: cf-templates-f5lkgopzuq9c-eu-central-1
  UploadedResources: qa_lambda.zip
  LambdaName: LambdaProcessingQA